// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using System.Threading.Tasks;
using ObjCRuntime;
using System.Threading;
using CoreFoundation;

namespace TestFinalizerRunloop
{
    public partial class ViewControllerReleaseWhenClosed : NSViewController
    { 

        NSButton button;
        public ViewControllerReleaseWhenClosed(IntPtr handle) : base(handle)
        {
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            button = new NSButton { Title = "Create Views" };
            View.AddSubview(button);
            button.Frame = new CoreGraphics.CGRect(0, 0, 200, 50);
            button.Activated += Button_Activated;

            //var raise = new Selector("raise");
            //new NSException("a", "a", null).PerformSelector(raise);
        }

        public override void ViewDidAppear()
        {
            Console.WriteLine("ViewDidAppear");

            base.ViewDidAppear();
        }
        public override void ViewDidDisappear()
        {
            button.Activated -= Button_Activated;
            button.Target = null;

            Console.WriteLine("ViewDidDisappear");

            base.ViewDidDisappear();
        }

        NSView MakePrintingSubviews()
        {
            var sv = new FinalizableView();
            sv.AddSubview(new FinalizableView());

            return sv;
        }

        private void Button_Activated(object sender, EventArgs e)
        {
            Console.WriteLine("Button activated: {0}", View.Window.Title);

            var sv = MakePrintingSubviews();

            Console.WriteLine("Expecting 2 non-null");
            button.AddSubview(sv);

            Console.WriteLine("Expecting 2 null");
            button.RemoveFromSuperview();

            Console.WriteLine("Expecting nothing");
            sv.RemoveFromSuperview();

            Console.WriteLine("Expecting nothing");
            button.AddSubview(sv);

            Console.WriteLine("Expecting 2 non-null");
            View.AddSubview(button);

            Console.WriteLine("Expecting 2 null");
            sv.RemoveFromSuperview();

            Console.WriteLine("Expecting 2 non-null");
            button.AddSubview(sv);

            Console.WriteLine("Expecting 2 null");

            BeginInvokeOnMainThread(() =>
            {
                var window = View.Window;
                window.DangerousRetain();
                window.Close();
                window.DangerousAutorelease();
                //var controller = (NSWindowController)window.WindowController;
                //controller.Close();
            });
        }

    }
}
